[## MAIN ##]
[ScreenProducer]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenOpening
[ScreenOpening]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenCredit
[ScreenCredit]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenDemonstration
[ScreenDemonstration]
SecondsToShow=30
NextScreen=ScreenRanking
Fallback=ScreenGameplay
DifficultiesToShow=easy,medium
[ScreenEvaluation]
; JUDGMENT
ShowPeakComboAward=0
ShowPerDifficultyAward=0

ShowMarvelous=0
ShowMarvelousAs=Perfect
ShowCheckpoints=0
ShowCheckpointAs=Perfect
ShowHidden=0
ShowHiddenAs=Hidden
ShowMines=0
ShowHitMineAs=HitMine
ShowPotions=0
ShowHitPotionAs=HitPotion
ShowShocks=0
ShowHitShockAs=HitShock
ShowNoneAs=None
ShowOK=0
[ScreenOptionsMenu]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
NextScreen=ScreenProducer
PrevScreen=ScreenProducer

LineNames=1,2,3,4,5,6,7,8
OptionMenuFlags=together;forceallplayers;smnavigation

Line1=list,Input Test
Line2=list,Config Key/Joy Mappings
Line3=list,Profile Options
Line4=list,Appearance Options
Line5=list,Gameplay Options
Line6=list,Machine Options
Line7=list,Reload Songs/Courses
Line8=list,Reset To Defaults
[## BRANCHES ##]
[ScreenBranchGradePlayers]
Class=ScreenBranch
Choices=1,2,3
Condition1=IsHumanPlayer(1) and IsHumanPlayer(2)
Condition2=IsHumanPlayer(1) and not IsHumanPlayer(2)
Condition3=IsHumanPlayer(2) and not IsHumanPlayer(1)
NextScreen1=Screen,ScreenBranchGrade;
NextScreen2=Screen,ScreenBranchGrade1P;
NextScreen3=Screen,ScreenBranchGrade2P;
[ScreenBranchGrade]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(1) == 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 0 and GetGrade(2) <= GetGrade(1) or GetGrade(1) == 1 and GetGreats(1) == 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 1 and GetGreats(2) == 0 and GetGrade(2) <= GetGrade(1)
Condition2=GetGrade(1) == 1 and GetGreats(1) > 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 1 and GetGreats(2) > 0 and GetGrade(2) <= GetGrade(1)
Condition3=GetGrade(1) == 2 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 2 and GetGrade(2) <= GetGrade(1)
Condition4=GetGrade(1) == 3 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 3 and GetGrade(2) <= GetGrade(1)
Condition5=GetGrade(1) == 4 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 4 and GetGrade(2) <= GetGrade(1)
Condition6=GetGrade(1) == 5 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 5 and GetGrade(2) <= GetGrade(1)
Condition7=GetGrade(1) == 6 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 6 and GetGrade(2) <= GetGrade(1)
Condition8=GetGrade(1) == 7 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 7 and GetGrade(2) <= GetGrade(1)
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;
[ScreenBranchGrade1P]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(1) == 0 or GetGrade(1) == 1 and GetGreats(1) == 0
Condition2=GetGrade(1) == 1 and GetGreats(1) > 0
Condition3=GetGrade(1) == 2
Condition4=GetGrade(1) == 3
Condition5=GetGrade(1) == 4
Condition6=GetGrade(1) == 5
Condition7=GetGrade(1) == 6
Condition8=GetGrade(1) == 7
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;
[ScreenBranchGrade2P]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(2) == 0 or GetGrade(2) == 1 and GetGreats(2) == 0
Condition2=GetGrade(2) == 1 and GetGreats(2) > 0
Condition3=GetGrade(2) == 2
Condition4=GetGrade(2) == 3
Condition5=GetGrade(2) == 4
Condition6=GetGrade(2) == 5
Condition7=GetGrade(2) == 6
Condition8=GetGrade(2) == 7
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;
[## OPTIONS ##]
[ScreenOperatorMenu]
Fallback=ScreenWithMenuElements
PrevScreen=ScreenOptionsMenu
NextScreen=ScreenOptionsMenu

ShrinkTextIfTooLong=0
CapitalizeAllOptionNames=0
StyleIcon=0
MemoryCardIcons=0

TimerSeconds=0
TimerOnCommand=hidden,1
[ScreenInputTest]
Fallback=ScreenOperatorMenu
Class=ScreenTestInput
[ScreenMapControllers]
Fallback=ScreenOperatorMenu
EvenLineIn=
OddLineIn=
EvenLineOut=
OddLineOut=

TitleX=GetScreenWidth() * 0.5
TitleY=-6
TitleShadowLength=0
TitleZoom=1

SubtitleX=GetScreenWidth() * 0.5
SubtitleY=6
SubtitleShadowLength=0
SubtitleZoom=1

Column1X=GetScreenWidth() * 0.1
Column2X=GetScreenWidth() * 0.2
Column3X=GetScreenWidth() * 0.3
Column4X=GetScreenWidth() * 0.7
Column5X=GetScreenWidth() * 0.8
Column6X=GetScreenWidth() * 0.9

EntryShadowLength=0
EntryZoom=0.7

LineStartY=64
LineHeight=28

ErrorColor=1,0,0,0
ErrorX=GetScreenWidth() * 0.5
ErrorY=GetScreenHeight() * 0.5
ErrorZoom=1
[ScreenProfileOptions]
Fallback=ScreenOperatorMenu
[ScreenAppearanceOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=list,Center Image
Line2=conf,Language
Line3=conf,Theme
Line4=conf,DefaultNoteSkin
Line5=conf,DisplayMode
Line6=conf,DisplayResolution
Line7=conf,DisplayColor
Line8=conf,TextureResolution
Line9=conf,TextureColor
Line10=conf,MovieColor
Line11=conf,SmoothLines
Line12=conf,CelShadeModels
Line13=conf,KeepTexturesInMemory
Line14=conf,RefreshRate
Line15=conf,WaitForVsync
[ScreenCenterImage]
Fallback=ScreenOperatorMenu
[ScreenGameplayOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=list,Background Options
Line2=list,Display Options
Line3=list,Judgement and Scoring Options
Line4=list,Song Selection Options
Line5=list,Extra Stage Options
Line6=conf,Game
[ScreenBackgroundOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8,9
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,Brightness
Line2=conf,BackgroundMode
Line3=conf,RandomBackgrounds
Line4=conf,StartRandomBGAwMusic
Line5=conf,EndRandomBGAwMusic
Line6=conf,FadeBGOnChange
Line7=conf,Danger
Line8=conf,DancingCharacters
Line9=conf,BeginnerHelper
[ScreenDisplayOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,ScoreDisplay
Line2=conf,OniScoreDisplay
Line3=conf,SoloSingles
Line4=conf,StageFinishesWithMusic
Line5=conf,ChangeSpeedWithNumkeys
Line6=conf,SaveSpeedWithNumkeys
Line7=conf,Lyrics
Line8=conf,BackDelayed
[ScreenJSOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,AutoPlay
Line2=conf,AutoPlayCombo
Line3=conf,ScoringType
Line4=conf,DefaultFailType
Line5=conf,MarvelousTiming
Line6=conf,JudgeDifficulty
Line7=conf,JudgeDifficultyAfter
Line8=conf,LifeDifficulty
Line9=conf,ProgressiveLifebar
Line10=conf,ProgressiveStageLifebar
Line11=conf,ProgressiveNonstopLifebar
Line12=conf,ProgressiveLifebarbySong
Line13=conf,PumpItUpHoldNotes
Line14=conf,MissComboIncOnBreak
Line15=conf,ComboBreaksOnGood
Line16=conf,ComboBreaksOnMines
Line17=conf,ComboIncreasesOnPotions
Line18=conf,ComboIncreasesOnRollHits
Line19=conf,ComboIncreasesOnHoldOK
Line20=conf,ComboBreaksOnHoldNG
[ScreenSongSelOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8,9,10,11,12
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,ShowSongOptions
Line2=conf,WheelSpeed
Line3=conf,SongGroup
Line4=conf,WheelSections
Line5=conf,CourseSort
Line6=conf,PlayerSongs
Line7=conf,HiddenSongs
Line8=conf,UnlockSystem
Line9=conf,RandomAtEnd
Line10=conf,Translations
Line11=conf,EventModeIgnoresSelectable
Line12=conf,EventModeIgnoresUnlock
[ScreenExtraStageOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,AllowExtraStage
Line2=conf,PickExtraStage
Line3=conf,PickModsInExtraStage
Line4=conf,UseDarkInExtraStage
Line5=conf,UseOniForExtraStage1
Line6=conf,UseOniForExtraStage2
[ScreenMachineOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=list,Sound Options
Line2=list,Clear Machine Stats
Line3=conf,SongsPerPlay
Line4=conf,EventMode
Line5=conf,MenuTimer
Line6=conf,AutoMapOnJoyChange
Line7=conf,MenuButtons
Line8=conf,OptionsNavigation
Line9=conf,AutogenSteps
Line10=conf,AutogenGroupCourses
Line11=conf,FastLoad
Line12=conf,ShowNameEntry
Line13=conf,ShowStats
Line14=conf,ShowBanners
Line15=conf,EasterEggs
Line16=conf,Instructions
Line17=conf,Caution
Line18=conf,UseMemoryCards
[ScreenSoundOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu

LineNames=1,2,3,4,5,6
OptionMenuFlags=together;explanations;forceallplayers;smnavigation
Line1=conf,SoundVolume
Line2=conf,AttractSoundFrequency
Line3=conf,Announcer
Line4=conf,PositiveAnnouncerOnly
Line5=conf,PlayAttackSounds
Line6=conf,ResamplingQuality
[ScreenReloadSongs]
Fallback=ScreenOperatorMenu
[ScreenResetToDefaults]
Fallback=ScreenOperatorMenu
NextScreen=ScreenOptionsMenu
[## FALLBACKS ##]
[ScreenAttract]
ScreenMenuStartPressed=ScreenTitleMenu
JoinPlayersOnStart=1

CreditsP1OnCommand=hidden,1;
CreditsP1X=170
CreditsP1Y=685
CreditsP2OnCommand=hidden,1;
CreditsP2X=933
CreditsP2Y=685

UseCreditSound=1
UseMenuBack=0
[## SYSTEM ##]
[ScreenOptionsMaster]
# MAIN OPTIONS
Input Test=1,together
Input TestDefault=
Input Test,1=screen,ScreenInputTest;name,InputTest

Config Key/Joy Mappings=1,together
Config Key/Joy MappingsDefault=
Config Key/Joy Mappings,1=screen,ScreenMapControllers;name,KeyJoyMappings

Profile Options=1,together
Profile OptionsDefault=
Profile Options,1=screen,ScreenProfileOptions;name,ProfileOptions

Appearance Options=1,together
Appearance OptionsDefault=
Appearance Options,1=screen,ScreenAppearanceOptions;name,AppearanceOptions

Gameplay Options=1,together
Gameplay OptionsDefault=
Gameplay Options,1=screen,ScreenGameplayOptions;name,GameplayOptions

Machine Options=1,together
Machine OptionsDefault=
Machine Options,1=screen,ScreenMachineOptions;name,MachineOptions

Reload Songs/Courses=1,together
Reload Songs/CoursesDefault=
Reload Songs/Courses,1=screen,ScreenReloadSongs;name,ReloadSongs

Reset To Defaults=1,together
Reset To DefaultsDefault=
Reset To Defaults,1=screen,ScreenResetToDefaults;name,ResetToDefaults

# SUB OPTIONS
Center Image=1,together
Center ImageDefault=
Center Image,1=screen,ScreenCenterImage;name,CenterImage

Background Options=1,together
Background OptionsDefault=
Background Options,1=screen,ScreenBackgroundOptions;name,BackgroundOptions

Display Options=1,together
Display OptionsDefault=
Display Options,1=screen,ScreenDisplayOptions;name,DisplayOptions

Judgement and Scoring Options=1,together
Judgement and Scoring OptionsDefault=
Judgement and Scoring Options,1=screen,ScreenJSOptions;name,JSOptions

Song Selection Options=1,together
Song Selection OptionsDefault=
Song Selection Options,1=screen,ScreenSongSelOptions;name,SongSelOptions

Extra Stage Options=1,together
Extra Stage OptionsDefault=
Extra Stage Options,1=screen,ScreenExtraStageOptions;name,ExtraStageOptions

Sound Options=1,together
Sound OptionsDefault=
Sound Options,1=screen,ScreenSoundOptions;name,SoundOptions

Clear Machine Stats=1,together
Clear Machine StatsDefault=
Clear Machine Stats,1=screen,ScreenClearMachineStats;name,ClearMachineStats

# SCREEN COMMAND MENU
Speed=11
SpeedDefault=mod,1x,no boost,no brake,no expand
Speed,1=mod,1x;name,x1
Speed,2=mod,2x;name,x2
Speed,3=mod,2.5x;name,x2.5
Speed,4=mod,3x;name,x3
Speed,5=mod,3.5x;name,x3.5
Speed,6=mod,4x;name,x4
Speed,7=mod,4.5x;name,x4.5
Speed,8=mod,5x;name,x5
Speed,9=mod,6x;name,x6
Speed,9=mod,boost;name,Boost;
Speed,10=mod,brake;name,Brake;
Speed,11=mod,expand;name,Expand;

Display=6,multiselect
DisplayDefault=mod,no hidden,no stealth,no sudden,no dark,no blink,no randombg
Display,1=mod,hidden;name,Hidden;
Display,2=mod,stealth;name,Stealth;
Display,3=mod,sudden;name,Sudden
Display,4=mod,dark;name,Dark
Display,5=mod,blink;name,Blink
Display,6=mod,randombg;name,RandomBG

Path=6,multiselect
PathDefault=mod,0� z-rotation,no centered,no distant,no tiny,no converge,no tornado,no bumpy,no reverse
Path,1=mod,centered,180% distant,125% tiny,200% converge;name,Space;
Path,2=mod,underattack;name,UnderAttack
Path,3=mod,reverse;name,DropPIU
Path,4=mod,30% Tornado;name,Snake
Path,5=mod,0.3x,-750% bumpy,87.5% converge,-350% reverse;name,Sink
Path,6=mod,0.4x,650% bumpy,87.5% converge,-350% reverse;name,Rise

Alternate=1,multiselect
AlternateDefault=mod,no backwards
Alternate,1=mod,backwards;name,Backwards

Judge=2,multiselect
JudgeDefault=mod,no reversegrade,normal-drain
Judge,1=mod,reversegrade;name,ReverseJudgment
Judge,2=mod,norecover;name,NoRecover

Rush=5
RushDefault=mod,1.0xmusic
Rush,1=name,Off
Rush,2=mod,0.8xmusic,randombg;name,0.8x
Rush,3=mod,1.1xmusic,randombg;name,1.1x
Rush,4=mod,1.2xmusic,randombg;name,1.2x
Rush,5=mod,1.5xmusic,randombg;name,1.5x

PlayerAutoPlay=2
PlayerAutoPlayDefault=mod,no playerautoplay
PlayerAutoPlay,1=mod,no playerautoplay;name,Off
PlayerAutoPlay,2=mod,playerautoplay;name,On
##
[CustomScoring]
ComboIsPerRow=0
ComboAboveThresholdAddsToScoreBonus=0
ComboScoreBonusThreshold=50
ComboScoreBonusValue=+1000

BaseNoteScoreMultiplier=1.0
DoubleNoteScoreMultiplier=1.0
TripleNoteScoreMultiplier=1.0
QuadOrHigherNoteScoreMultiplier=1.0

PointsMarvelous=+1000
PointsPerfect=+1000
PointsGreat=+500
PointsGood=+100
PointsBoo=-200
PointsMiss=-500
PointsHitMine=-500
PointsHitShock=-500
PointsHitPotion=+1000
PointsHoldOK=+1000
PointsHoldNG=-500
PointsRollOK=+1000
PointsRollNG=-500
[FadingBanner]
FadeSeconds=0
[FadingBackground]
FadeSeconds=0
[SongManager]
NumGroupColors=1
BeginnerColor=1,1,1,1
EasyColor=1,1,1,1
MediumColor=1,1,1,1
HardColor=1,1,1,1
ChallengeColor=1,1,1,1
EditColor=1,1,1,1
HiddenColor=1,1,1,1
ExtraColor=1,1,1,1
ExtraColorMeter=99
ExtraColorMeterITG=99
ExtraColorMeterX=99
ExtraColorMeterNX2=99