[## MAIN ##]
[ScreenProducer]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenOpening
[ScreenOpening]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenCredit
[ScreenCredit]
Class=ScreenAttract
Fallback=ScreenAttract
NextScreen=ScreenDemonstration
[ScreenDemonstration]
SecondsToShow=30
NextScreen=ScreenRanking
Fallback=ScreenGameplay
DifficultiesToShow=easy,medium

CreditsP1OnCommand=hidden,1;
CreditsP2OnCommand=hidden,1;
[ScreenEvaluation]
; JUDGMENT
ShowPeakComboAward=0
ShowPerDifficultyAward=0

ShowMarvelous=0
ShowMarvelousAs=Perfect
ShowCheckpoints=0
ShowCheckpointAs=Perfect
ShowHidden=0
ShowHiddenAs=Hidden
ShowMines=0
ShowHitMineAs=HitMine
ShowPotions=0
ShowHitPotionAs=HitPotion
ShowShocks=0
ShowHitShockAs=HitShock
ShowNoneAs=None
ShowOK=0
[ScreenOptionsMenu]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
NextScreen=ScreenProducer
PrevScreen=ScreenProducer
[ScreenCommandMenu]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
PrevScreen=ScreenBranchPlayers
NextScreen=ScreenTitleCard

ShrinkTextIfTooLong=0
CapitalizeAllOptionNames=0

LineNames=1,2,3,4,5,6,7
OptionMenuFlags=toggle

Line1=list,Speed
Line2=list,NoteSkins
Line3=list,Display
Line4=list,Path
Line5=list,Alternate
Line6=list,Judge
Line7=list,Rush
Line8=conf,PortraitTheme

CancelAllP1X=
CancelAllP1Y=
CancelAllP1OnCommand=
CancelAllP1ShowCommand=
CancelAllP2X=
CancelAllP2Y=
CancelAllP2OnCommand=
CancelAllP2ShowCommand=

[## BRANCHES ##]
[ScreenBranchGradePlayers]
Class=ScreenBranch
Choices=1,2,3
Condition1=IsHumanPlayer(1) and IsHumanPlayer(2)
Condition2=IsHumanPlayer(1) and not IsHumanPlayer(2)
Condition3=IsHumanPlayer(2) and not IsHumanPlayer(1)
NextScreen1=Screen,ScreenBranchGrade;
NextScreen2=Screen,ScreenBranchGrade1P;
NextScreen3=Screen,ScreenBranchGrade2P;
[ScreenBranchGrade]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(1) == 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 0 and GetGrade(2) <= GetGrade(1) or GetGrade(1) == 1 and GetGreats(1) == 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 1 and GetGreats(2) == 0 and GetGrade(2) <= GetGrade(1)
Condition2=GetGrade(1) == 1 and GetGreats(1) > 0 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 1 and GetGreats(2) > 0 and GetGrade(2) <= GetGrade(1)
Condition3=GetGrade(1) == 2 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 2 and GetGrade(2) <= GetGrade(1)
Condition4=GetGrade(1) == 3 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 3 and GetGrade(2) <= GetGrade(1)
Condition5=GetGrade(1) == 4 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 4 and GetGrade(2) <= GetGrade(1)
Condition6=GetGrade(1) == 5 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 5 and GetGrade(2) <= GetGrade(1)
Condition7=GetGrade(1) == 6 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 6 and GetGrade(2) <= GetGrade(1)
Condition8=GetGrade(1) == 7 and GetGrade(1) <= GetGrade(2)  or  GetGrade(2) == 7 and GetGrade(2) <= GetGrade(1)
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;
[ScreenBranchGrade1P]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(1) == 0 or GetGrade(1) == 1 and GetGreats(1) == 0
Condition2=GetGrade(1) == 1 and GetGreats(1) > 0
Condition3=GetGrade(1) == 2
Condition4=GetGrade(1) == 3
Condition5=GetGrade(1) == 4
Condition6=GetGrade(1) == 5
Condition7=GetGrade(1) == 6
Condition8=GetGrade(1) == 7
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;
[ScreenBranchGrade2P]
Class=ScreenBranch
Choices=1,2,3,4,5,6,7,8,9
Condition1=GetGrade(2) == 0 or GetGrade(2) == 1 and GetGreats(2) == 0
Condition2=GetGrade(2) == 1 and GetGreats(2) > 0
Condition3=GetGrade(2) == 2
Condition4=GetGrade(2) == 3
Condition5=GetGrade(2) == 4
Condition6=GetGrade(2) == 5
Condition7=GetGrade(2) == 6
Condition8=GetGrade(2) == 7
Condition9=true
NextScreen1=Screen,ScreenEvaluationSS;
NextScreen2=Screen,ScreenEvaluationS+;
NextScreen3=Screen,ScreenEvaluationS;
NextScreen4=Screen,ScreenEvaluationA;
NextScreen5=Screen,ScreenEvaluationB;
NextScreen6=Screen,ScreenEvaluationC;
NextScreen7=Screen,ScreenEvaluationD;
NextScreen8=Screen,ScreenEvaluationF;
NextScreen9=Screen,ScreenEvaluation;

[## OPTIONS ##]
[ScreenOperatorMenu]
Fallback=ScreenWithMenuElements
PrevScreen=ScreenOptionsMenu
NextScreen=ScreenOptionsMenu

ShrinkTextIfTooLong=0
CapitalizeAllOptionNames=0
StyleIcon=0
MemoryCardIcons=0

TimerSeconds=0
TimerOnCommand=hidden,1
[ScreenInputTest]
Fallback=ScreenOperatorMenu
Class=ScreenTestInput
[ScreenMapControllers]
Fallback=ScreenOperatorMenu
EvenLineIn=
OddLineIn=
EvenLineOut=
OddLineOut=

TitleX=GetScreenWidth() * 0.5
TitleY=-6
TitleShadowLength=0
TitleZoom=1

SubtitleX=GetScreenWidth() * 0.5
SubtitleY=6
SubtitleShadowLength=0
SubtitleZoom=1

Column1X=GetScreenWidth() * 0.1
Column2X=GetScreenWidth() * 0.2
Column3X=GetScreenWidth() * 0.3
Column4X=GetScreenWidth() * 0.7
Column5X=GetScreenWidth() * 0.8
Column6X=GetScreenWidth() * 0.9

EntryShadowLength=0
EntryZoom=0.7

LineStartY=64
LineHeight=28

ErrorColor=1,0,0,0
ErrorX=GetScreenWidth() * 0.5
ErrorY=GetScreenHeight() * 0.5
ErrorZoom=1
[ScreenProfileOptions]
Fallback=ScreenOperatorMenu
[ScreenAppearanceOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenCenterImage]
Fallback=ScreenOperatorMenu
[ScreenGameplayOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenBackgroundOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenDisplayOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenJSOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenSongSelOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenExtraStageOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenMachineOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenSoundOptions]
Class=ScreenOptionsMaster
Fallback=ScreenOperatorMenu
[ScreenReloadSongs]
Fallback=ScreenOperatorMenu
[ScreenResetToDefaults]
Fallback=ScreenOperatorMenu
NextScreen=ScreenOptionsMenu

[## FALLBACKS ##]
[ScreenAttract]
ScreenMenuStartPressed=ScreenTitleMenu
ScreenMenuBackPressed=ScreenProducer
JoinPlayersOnStart=1

CreditsP1OnCommand=hidden,1;
CreditsP1X=170
CreditsP1Y=685
CreditsP2OnCommand=hidden,1;
CreditsP2X=933
CreditsP2Y=685

UseCreditSound=1
UseMenuBack=0

[## SYSTEM ##]
[CodeDetector]
BackInEventMode=
Backwards=
CancelAll=
CancelAllPlayerOptions=
Dark=
Drop=
Easier1=
Easier2=
Harder1=
Harder2=
Hidden=
HoldNotes=
Left=
LeftAttack=
Mines=
Mirror=
ModeMenu1=
ModeMenu2=
NextAccel=
NextAnnouncer=
NextAnnouncer2=
NextAppearance=
NextBannerGroup=
NextBannerGroup2=
NextEffect=
NextGame=
NextGame2=
NextScrollSpeed=
NextSort1=
NextSort2=
NextSort3=
NextSort4=
NextTheme=
NextTheme2=
NextTransform=
NextTurn=
Potions=
PreviousBannerGroup=
PreviousBannerGroup2=
PreviousScrollSpeed=
RandomVanish=
Reverse=
ReverseGrade=
Right=
RightAttack=
RollNotes=
SaveScreenshot=
UseScrollSpeedList=0
ScrollSpeedList=
Shocks=
Shuffle=
SortMenu1=
SortMenu2=
SuperShuffle=
UnderAttack=
CommandWindow=DownLeft,DownRight,DownLeft,DownRight,DownLeft,DownRight
[ScreenOptionsMaster]
# MAIN OPTIONS
# SCREEN COMMAND MENU
Speed=20
SpeedDefault=mod,1x,no boost,no brake,no expand
Speed,1=mod,P400;name,P400
Speed,2=mod,P450;name,P450
Speed,3=mod,P500;name,P500
Speed,4=mod,P550;name,P550
Speed,5=mod,P600;name,P600
Speed,6=mod,P650;name,P650
Speed,7=mod,P700;name,P700
Speed,8=mod,boost;name,Acceleration;
Speed,9=mod,brake;name,Deceleration;
Speed,10=mod,expand;name,Earthworm;
Speed,11=mod,1x;name,x1
Speed,12=mod,2x;name,x2
Speed,13=mod,2.5x;name,x2.5
Speed,14=mod,3x;name,x3
Speed,15=mod,3.5x;name,x3.5
Speed,16=mod,4x;name,x4
Speed,17=mod,4.5x;name,x4.5
Speed,18=mod,5x;name,x5
Speed,19=mod,5.5x;name,x5.5
Speed,20=mod,6x;name,x6

Display=6,multiselect
DisplayDefault=mod, no hidden, no stealth, no sudden, no dark, no blink, no static
Display,1=mod,hidden;name,Vanish
Display,2=mod,stealth;name,Nonstep
Display,3=mod,sudden;name,Appear
Display,4=mod,dark;name,Freedom
Display,5=mod,blink;name,Flash
Display,6=mod,static;name,BGAOFF;

Path=6,multiselect
PathDefault=mod,0� z-rotation,no centered,no distant,no tiny,no converge,no tornado,no bumpy,no reverse
Path,1=mod,centered,180% distant,125% tiny,200% converge;name,NX;
Path,2=mod,underattack;name,UnderAttack
Path,3=mod,reverse;name,DropPIU
Path,4=mod,30% Tornado;name,Snake
Path,5=mod,0.3x,-750% bumpy,87.5% converge,-350% reverse;name,Sink
Path,6=mod,0.4x,650% bumpy,87.5% converge,-350% reverse;name,Rise

Alternate=3,multiselect
AlternateDefault=mod,no backwards,no supershuffle,no holdrolls
Alternate,1=mod,backwards;name,Mirror
Alternate,2=mod,supershuffle;name,RandomStep
Alternate,3=mod,holdrolls;name,Runner

Judge=2,multiselect
JudgeDefault=mod,no blind,no reversegrade
Judge,1=mod,blind;name,Hide
Judge,2=mod,reversegrade;name,ReverseJudgment

Rush=8
RushDefault=mod,1.0xmusic, no static
Rush,1=mod,0.8xmusic,static;name,0.8x
Rush,2=mod,0.9xmusic,static;name,0.9x
Rush,3=mod,1.0xmusic,no static;name,1.0x
Rush,4=mod,1.1xmusic,static;name,1.1x
Rush,5=mod,1.2xmusic,static;name,1.2x
Rush,6=mod,1.3xmusic,static;name,1.3x
Rush,7=mod,1.4xmusic,static;name,1.4x
Rush,8=mod,1.5xmusic,static;name,1.5x

PlayerAutoPlay=2
PlayerAutoPlayDefault=mod,no playerautoplay
PlayerAutoPlay,1=mod,no playerautoplay;name,Off
PlayerAutoPlay,2=mod,playerautoplay;name,On
##
[CustomScoring]
ComboIsPerRow=0
ComboAboveThresholdAddsToScoreBonus=0
ComboScoreBonusThreshold=50
ComboScoreBonusValue=+1000

BaseNoteScoreMultiplier=1.0
DoubleNoteScoreMultiplier=1.0
TripleNoteScoreMultiplier=1.0
QuadOrHigherNoteScoreMultiplier=1.0

PointsMarvelous=+1000
PointsPerfect=+1000
PointsGreat=+500
PointsGood=+100
PointsBoo=-200
PointsMiss=-500
PointsHitMine=-500
PointsHitShock=-500
PointsHitPotion=+1000
PointsHoldOK=+1000
PointsHoldNG=-500
PointsRollOK=+1000
PointsRollNG=-500
[FadingBanner]
FadeSeconds=0
[FadingBackground]
FadeSeconds=0
[SongManager]
NumGroupColors=1
BeginnerColor=1,1,1,1
EasyColor=1,1,1,1
MediumColor=1,1,1,1
HardColor=1,1,1,1
ChallengeColor=1,1,1,1
EditColor=1,1,1,1
HiddenColor=1,1,1,1
ExtraColor=1,1,1,1
ExtraColorMeter=99
ExtraColorMeterITG=99
ExtraColorMeterX=99
ExtraColorMeterNX2=99
